parameters:

services:
    sadbot_video.hello.menu.voter.request:
        class: Sadbot\Bundle\VideoBundle\Menu\RequestVoter
        arguments:
            - @service_container
        tags:
            - { name: knp_menu.voter }
