Sadbot\Bundle\VideoBundle\Form\VideoType:
    constraints:
        - Sonata\AdminBundle\Validator\Constraints\InlineConstraint:
            service: sadbot.validation.video_apply
            method: validate