_audio:
    path:     /
    defaults: { _controller: "SadbotVideoBundle:Audio:index" }

_audio_show:
    path:     /{id}/show
    defaults: { _controller: "SadbotVideoBundle:Audio:show" }

_audio_upload:
    path:     /upload
    defaults: { _controller: "SadbotVideoBundle:Audio:upload" }

_audio_create:
    path:     /create
    defaults: { _controller: "SadbotVideoBundle:Audio:create" }
    methods: [POST]

_audio_edit:
    path:     /{id}/edit
    defaults: { _controller: "SadbotVideoBundle:Audio:edit" }

_audio_update:
    path:     /{id}/update
    defaults: { _controller: "SadbotVideoBundle:Audio:update" }
    methods:  [POST, PUT]

_audio_delete:
    path:     /{id}/delete
    defaults: { _controller: "SadbotVideoBundle:Audio:delete" }
    methods:  [POST, DELETE]


_audio_download:
  path:   /download/{id}
  defaults: { _controller: "SadbotVideoBundle:Audio:download" }