test:
    path: /test
    defaults: { _controller: "SadbotVideoBundle:Photo:test" }



_photo:
    path:     /
    defaults: { _controller: "SadbotVideoBundle:Photo:index" }

_photo_show:
    path:     /{id}/show
    defaults: { _controller: "SadbotVideoBundle:Photo:show" }

_photo_upload:
    path:     /upload
    defaults: { _controller: "SadbotVideoBundle:Photo:upload" }

_photo_create:
    path:     /create
    defaults: { _controller: "SadbotVideoBundle:Photo:create" }
    methods:  POST

_photo_edit:
    path:     /{id}/edit
    defaults: { _controller: "SadbotVideoBundle:Photo:edit" }

_photo_update:
    path:     /{id}/update
    defaults: { _controller: "SadbotVideoBundle:Photo:update" }
    methods:  [POST, PUT]

_photo_delete:
    path:     /{id}/delete
    defaults: { _controller: "SadbotVideoBundle:Photo:delete" }
    methods:  [POST, DELETE]


_photo_download:
  path:   /download/{id}
  defaults: { _controller: "SadbotVideoBundle:Photo:download" }