_video:
  path: /
  defaults: { _controller: SadbotVideoBundle:Video:index }

_video_upload:
  path: /upload
  defaults: { _controller: SadbotVideoBundle:Video:upload }

_video_create:
  path: /create
  defaults: { _controller: SadbotVideoBundle:Video:create }
  methods: [POST]

_video_show:
  path: /{id}
  defaults: { _controller: SadbotVideoBundle:Video:show }

_video_edit:
  path: /{id}/edit
  defaults: { _controller: SadbotVideoBundle:Video:edit }

_video_update:
  path: /{id}
  defaults: { _controller: SadbotVideoBundle:Video:update }
  methods: [POST,PUT]

_video_delete:
  path: /{id}
  defaults: { _controller: SadbotVideoBundle:Video:delete }
  methods: [POST,DELETE]